// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AlphabetizeMe
{
    internal sealed partial class Vsix
    {
        public const string Id = "AlphabetizeMe.b8339106-182a-4d49-ae48-3181bac72375";
        public const string Name = "AlphabetizeMe";
        public const string Description = @"Highlight class members, right-click, Alphabetize to sort alphabetically. Simple.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
